package io.github.naimjeg.damagenexus.api.display;

public enum DamageContributionOperationKind {
    UNKNOWN,

    ADD_BASE_DAMAGE,
    ADD_TRUE_DAMAGE,

    ADD_APPLICATION_PRE_MULTIPLIER,
    ADD_CHANNEL_PRE_MULTIPLIER,
    ADD_GLOBAL_PRE_MULTIPLIER,

    ADD_CHANNEL_POST_MULTIPLIER,
    ADD_GLOBAL_POST_MULTIPLIER,

    ADD_TEMPORARY_RESISTANCE,
    ADD_CHANNEL_MITIGATION,
    ADD_GLOBAL_MITIGATION,
    MULTIPLY_ARMOR_EFFECTIVENESS,

    CONVERT_DAMAGE,
    GAIN_EXTRA_DAMAGE,

    OVERRIDE_FINAL_DAMAGE,
    CANCEL_DAMAGE
}
