package io.github.naimjeg.damagenexus.core.trace;

public enum DamageMutationType {
    BASE_DAMAGE,

    CANCEL_DAMAGE,

    CHANNEL_PRE_MULTIPLIER,
    APPLICATION_PRE_MULTIPLIER,
    GLOBAL_PRE_MULTIPLIER,

    CHANNEL_POST_MULTIPLIER,
    GLOBAL_POST_MULTIPLIER,

    CONVERSION,

    TEMPORARY_RESISTANCE,
    CHANNEL_MITIGATION,
    GLOBAL_MITIGATION,

    ARMOR_EFFECTIVENESS_MULTIPLIER,
    FINAL_OVERRIDE
}